<template>
  <div>
    <div class="list-container">
      <DxList
        :activeStateEnabled="false"
        :focusStateEnabled="false"
        :data-source="comments.data"
        :search-enabled="false"
      >
        <template #item="item">
          <div class="list-container">
            <div class="list-item d-flex js-space-between">
              <div>
                <div class="d-flex list--comments">
                  <div>
                    <img class="icon--type" :src="parseIconType(item.data.type)" />
                  </div>
                  <div>
                    <div class="list__content">
                      <i class="dx-icon dx-icon-user"></i>
                      <span class="text--bold">{{ item.data.author}}</span>
                    </div>
                    <div class="list__content">
                      <i class="dx-icon dx-icon-event"></i>
                      <span class="text--bold">{{formatDate(item.data.created)}}</span>
                    </div>
                  </div>
                </div>
                <div>
                  <div v-if="item.data.subject" class="subject">
                    <i class="dx-icon dx-icon-comment"></i>
                    <span
                      class="text--bold"
                    >{{translate(item.data.subject,item.data.isAutoGenerated)}}</span>
                  </div>
                </div>
              </div>
              <div class="status">
                <i :class="[parseIconStatus(item.data.status)]" class="dx-icon"></i>
                <span class="text--bold">{{converterStatus(item.data.status)}}</span>
              </div>
            </div>
          </div>
        </template>
      </DxList>
    </div>
    <div>
      <DxTextArea :on-value-changed="addComment" :height="90" :value="comment" />
    </div>
  </div>
</template>
<script>
import dataApi from "~/static/dataApi";
import DxList from "devextreme-vue/list";
import { DxTextArea } from "devextreme-vue";
import moment from "moment";
export default {
  components: {
    DxList,
    DxTextArea
  },
  props: ["taskId", "isCompleted"],
  data() {
    return {
      employees: [],
      comments: [],
      comment: ""
    };
  },
  async created() {
    this.comments = await this.$axios.get(dataApi.task.Texts + this.taskId);
    this.employees = await this.$axios.get(dataApi.company.Employee);
  },
  methods: {
    translate(text, isAutoGenerated) {
      if (isAutoGenerated) {
        return " " + this.$t(`translations.taskMessage.${text}`);
      }
      if (text) {
        return " " + text;
      }
    },
    converterStatus(status) {
      return " " + this.$t(`translations.taskMessage.${status}`);
    },
    parseIconStatus(status) {
      switch (status) {
        case "InProcess":
          return "dx-icon-clock";
          break;
      }
    },
    parseIconType(type) {
      switch (type) {
        case 0:
          return require("~/static/icons/iconAssignment/assignment.svg");
          break;
        case 3:
          return require("~/static/icons/iconAssignment/notice.svg");
      }
    },
    parseTypeText(type) {
      return " " + this.$t(`translations.commentType.${type}`);
    },
    formatDate(date) {
      return moment(date).format("L");
    },
    // pushComment() {
    //   if (this.comment) {
    //     this.comments.data.push({
    //       body: this.comment,
    //       created: new Date(),
    //       writtenById: {
    //         name: this.setAuthor(this.$store.getters["permissions/employeeId"])
    //           .name
    //       },
    //       isAutoGenerated: false
    //     });
    //     this.comment = "";
    //   }
    // },
    addComment(e) {
      this.$emit("addComment", e.value);
      this.comment = e.value;
    },
    setAllAuthor() {
      this.comments.data.map(async text => {
        text.writtenById = this.setAuthor(text.writtenById);
      });
    },
    setAuthor(id) {
      if (id === 7) {
        return { name: "Admin" };
      }
      return this.employees.data.data.find(user => {
        return user.id === id;
      });
    }
  }
};
</script>
<style lang="scss" scoped >
@import "~assets/themes/generated/variables.base.scss";
@import "~assets/dx-styles.scss";
.js-space-between {
  justify-items: flex-start;
  justify-content: flex-start;
  align-items: center;
  text-align: start;
  .status {
    margin-left: auto;
    padding: 0 5px;
    font-size: 20px;
    i {
      font-size: 25px;
    }
  }
}
.icon--type {
  display: flex;
  width: 40px;
}
.list-item {
  border-left: 5px solid green;
  border-radius: 2px;
  .subject {
    display: flex;
    flex-wrap: wrap;
    background: green;
    width: 300px;
    .text--bold {
      display: block;
      overflow: hidden;
      width: 300px;
    }
    padding: 10px 5px;
    font-size: 18px;
    .dx-icon-comment {
      font-size: 25px;
    }
  }
}

.text--bold {
  font-weight: 500;
}
</style>