<template>
  <div>
    <div class="list-container">
      <DxList :data-source="comments.data" :search-enabled="false">
        <template #item="item">
          <div>
            <div class="d-flex list--comments">
              <i class="dx-icon dx-icon-comment"></i>

              <div>
                <div class="list__content">
                  {{$t('translations.taskMessage.message')}}
                  <span
                    class="text--bold"
                  >{{translate(item.data.body,item.data.isAutoGenerated)}}</span>
                </div>
                <div class="list__content">
                  {{$t('translations.taskMessage.from')}}
                  <span
                    class="text--bold"
                  >{{ item.data.writtenById.name}}</span>
                </div>
                <div class="list__content">
                  {{$t('translations.taskMessage.created')}}
                  <span
                    class="text--bold"
                  >{{formatDate(item.data.created)}}</span>
                </div>
              </div>
              <div class="list__btn-group"></div>
            </div>
          </div>
        </template>
      </DxList>
    </div>
    <div>
      <DxTextArea :on-value-changed="addComment" :height="90" :value="comment" />
    </div>
  </div>
</template>
<script>
import dataApi from "~/static/dataApi";
import DxList from "devextreme-vue/list";
import { DxTextArea } from "devextreme-vue";
import moment from "moment";
export default {
  components: {
    DxList,
    DxTextArea
  },
  props: ["taskId", "isCompleted"],
  data() {
    return {
      employees: [],
      comments: [],
      comment: ""
    };
  },
  async created() {
    this.comments = await this.$axios.get(dataApi.task.Texts + this.taskId);
    this.employees = await this.$axios.get(dataApi.company.Employee);
    await this.setAllAuthor();
    this.$watch("isCompleted", this.pushComment);
  },
  methods: {
    translate(text, isAutoGenerated) {
      if (isAutoGenerated) {
        return this.$t(`translations.taskMessage.${text}`);
      }
      return text;
    },
    formatDate(date) {
      return moment(date).format("L");
    },
    pushComment() {
      if (this.comment) {
        this.comments.data.push({
          body: this.comment,
          created: new Date(),
          writtenById: {
            name: this.setAuthor(this.$store.getters["permissions/employeeId"])
              .name
          },
          isAutoGenerated: false
        });
        this.comment = "";
      }
    },
    addComment(e) {
      this.$emit("addComment", e.value);
      this.comment = e.value;
    },
    setAllAuthor() {
      this.comments.data.map(async text => {
        text.writtenById = this.setAuthor(text.writtenById);
      });
    },
    setAuthor(id) {
      if (id === 7) {
        return { name: "Admin" };
      }
      return this.employees.data.data.find(user => {
        return user.id === id;
      });
    }
  }
};
</script>
<style lang="scss" scoped >
@import "~assets/themes/generated/variables.base.scss";
@import "~assets/dx-styles.scss";
.list--comments {
  align-items: center;
  flex-wrap: wrap;
  .dx-icon-comment {
    border: 3px solid;
    border-radius: 30px;
    padding: 5px;
    margin: 0 5px;
    font-size: 25px;
  }
  .text--bold {
    font-weight: bold;
  }
  .list-container {
    border: 0.1px solid darken($base-bg, 15);
  

    height: 50vh;
    overflow: auto;
    width: 100%;
    i {
      display: inline;
    }
    .list__btn-group {
      margin-left: auto;
    }
  }
}
</style>