<template>
  <div>
    <div class="list-container">
      <DxList
        :activeStateEnabled="false"
        :focusStateEnabled="false"
        :data-source="comments.data"
        :search-enabled="false"
      >
        <template #item="item">
          <div class="list-container">
            <div class="list-item mY-2" :class="{'current-message':item.data.isCurrent}">
              <div class="d-flex js-space-between">
                <div>
                  <img class="icon--type" :src="parseIconType(item.data.type)" />
                </div>
                <div>
                  <div class="list__content">
                    <i class="dx-icon dx-icon-user"></i>
                    {{ item.data.author}}
                  </div>
                  <div class="list__content">
                    <i class="dx-icon dx-icon-event"></i>
                    {{formatDate(item.data.created)}}
                  </div>
                </div>
                <div class="task-state">
                  <div class="status">
                    <i :class="[parseIconStatus(item.data.status)]" class="dx-icon"></i>
                    {{converterStatus(item.data.status)}}
                  </div>
                  <div
                    v-if="item.data.isExpired"
                    class="expired"
                  >{{$t('translations.taskMessage.expired')}}</div>
                </div>
              </div>

              <div>
                <div v-if="item.data.subject" class="subject">
                  <span
                    class="text--bold"
                  >{{translate(item.data.subject,item.data.isAutoGenerated)}}</span>
                </div>
              </div>
            </div>

            <div
              class="list-item d-flex ml-4 mY-2"
              :class="{'current-message':message.isCurrent}"
              v-for="(message,index) in item.data.children"
              :key="index"
            >
              <div class="d-flex js-space-between">
                <div>
                  <img class="icon--type" :src="parseIconType(message.type)" />
                </div>
                <div>
                  <div class="list__content">
                    <i class="dx-icon dx-icon-user"></i>
                    {{ message.author}}
                  </div>
                  <div class="list__content">
                    <i class="dx-icon dx-icon-event"></i>
                    {{formatDate(message.created)}}
                  </div>
                </div>
                <div class="task-state">
                  <div class="status">
                    <i :class="[parseIconStatus(message.status)]" class="dx-icon"></i>
                    {{converterStatus(message.status)}}
                  </div>
                  <div
                    v-if="message.isExpired"
                    class="expired"
                  >{{$t('translations.taskMessage.expired')}}</div>
                </div>
              </div>
              <div>
                <div v-if="message.subject" class="subject">
                  <span class="text--bold">{{translate(message.subject,message.isAutoGenerated)}}</span>
                </div>
              </div>
            </div>
          </div>
        </template>
      </DxList>
    </div>
    <div>
      <DxTextArea :on-value-changed="addComment" :height="90" :value="comment" />
    </div>
  </div>
</template>
<script>
import dataApi from "~/static/dataApi";
import DxList from "devextreme-vue/list";
import { DxTextArea } from "devextreme-vue";
import moment from "moment";
export default {
  components: {
    DxList,
    DxTextArea
  },
  props: ["url"],
  data() {
    return {
      employees: [],
      comments: [],
      comment: ""
    };
  },
  async created() {
    this.comments = await this.$axios.get(this.url + this.$route.params.id);
    this.employees = await this.$axios.get(dataApi.company.Employee);
  },
  methods: {
    translate(text, isAutoGenerated) {
      if (isAutoGenerated) {
        return " " + this.$t(`translations.taskMessage.${text}`);
      }
      if (text) {
        return " " + text;
      }
    },
    converterStatus(status) {
      return " " + this.$t(`translations.taskMessage.${status}`);
    },
    parseIconStatus(status) {
      switch (status) {
        case "InProcess":
          return "dx-icon-clock";
        case "Unread":
          return "dx-icon-close";
      }
    },
    parseIconType(type) {
      switch (type) {
        case 0:
          return require("~/static/icons/iconAssignment/task.svg");
        case 3:
          return require("~/static/icons/iconAssignment/notice.svg");
        case 4:
          return require("~/static/icons/iconAssignment/assignment.svg");
      }
    },
    parseTypeText(type) {
      return " " + this.$t(`translations.commentType.${type}`);
    },
    formatDate(date) {
      return moment(date).format("L");
    },
    addComment(e) {
      this.$emit("addComment", e.value);
      this.comment = e.value;
    },
    setAllAuthor() {
      this.comments.data.map(async text => {
        text.writtenById = this.setAuthor(text.writtenById);
      });
    },
    setAuthor(id) {
      if (id === 7) {
        return { name: "Admin" };
      }
      return this.employees.data.data.find(user => {
        return user.id === id;
      });
    }
  }
};
</script>
<style lang="scss" scoped >
@import "~assets/themes/generated/variables.base.scss";
@import "~assets/dx-styles.scss";

.js-space-between {
  width: 100%;

  align-items: center;
}
.task-state {
  text-align: right;
  margin-left: auto;
  padding: 0 5px;
  font-size: 16px;
  i {
    font-size: 16px;
    margin: 0 5px;
  }
}
.mY-2 {
  margin: 20px 0;
}
.ml-4 {
  margin-left: 40px;
}
.current-message {
  background: $base-border-color;
}
.icon--type {
  display: flex;
  width: 30px;
  height: 100%;
}
.list-item {
  white-space: normal;
  border-left: 3px solid green;
  border-radius: 2px;
  .subject {
    .text--bold {
      display: block;
    }
    padding: 10px 5px;
    font-size: 14px;
  }
}
.expired {
  color: red;
}
.status {
  color: green;
  .dx-icon::before {
    color: green;
  }
}
.text--bold {
  font-weight: 500;
}
</style>